name: PlayerHider 
version: 1.0.0
main: de.spacenerd.playerhider.Playerhider
description: A Plugin to hide players from your perspective
author: Space Nerd 
website: https://spaceblog.medi.li
api-version: '1.21.4'

commands:
  friend:
    usage: "/friend <add/remove> <player name>"
    description: "command to add or remove friends"
